### ISSUE TITLE
Attention weights extraction

### ISSUE THREAD

**Issue by ahmedabuelnasr** [M-Nauta/TCDF#13]
Hello, your paper and the implementation are very interesting, I have a question regarding your implementation: 
2- How to extract the attention weights for the potential causes? 
Thank you.

**Comment by M-Nauta** [comment]
The attention scores are saved in `model.fs_attention`, and this parameter is also returned by the [train function](https://github.com/M-Nauta/TCDF/blob/82422321492effdf5666c7f7f1ca14196c41ed3d/TCDF.py#L41)
