### ISSUE TITLE
Scaling affecting results

### ISSUE THREAD

**Issue by kapkic** [M-Nauta/TCDF#14]
Hello,
Thank you for the paper and the work. I have a question regarding how TCDF interprets scaling.

Shouldn't TCDF be scale invariant, as the causes are related to the relationship between variables and values, not to their scaling?
For example, when we take one of the Financial dataset files (let's assume random-rels_20_1D_returns30007000_header in this example) and multiply every value by 100, ideally we should be getting the same causal relationships since we only change the scale of the data.

But in practice, the raw data returns 35 Causal predictions (X causes Y in T timesteps), and the raw data multiplied by 100 returns 51 predictions. I have noticed that in AD-DSTCN, a softmax function is applied, but I am unsure why even with that the scale creates a difference.

Thanks!

**Comment by M-Nauta** [comment]
Interesting finding. We didn't look into scaling in much detail. Softmax is not scale-invariant so together with the significance that might be related to the issue. If custom datasets have a different scaling than the datasets we used, I would recommend to scale the datasets accordingly.
