### ISSUE TITLE
Question: saving the causal graph

### ISSUE THREAD

**Issue by LynetteGao** [M-Nauta/TCDF#5]
Hi! I am wondering if there's option to save the resulting causal graph? Thanks

**Comment by M-Nauta** [comment]
Hi,
Saving the graph can be easily done by adapting the function `plotgraph` in `runTCDF.py` which creates G, a networkx digraph. [Documentation of networkx](https://networkx.org/documentation/stable/reference/readwrite/index.html#readwrite) describes how to write the graph to a file. For example, saving the graph as a JSON file is described [here](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.json_graph.node_link_data.html#networkx.readwrite.json_graph.node_link_data).
